# Generated by Django 4.2.5 on 2024-02-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(verbose_name='tarix')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson', models.CharField(max_length=100)),
                ('begin_date', models.DateTimeField(verbose_name='Qrupun dərsə başlama tarixi')),
                ('lesdays', models.CharField(choices=[('B.ertəsi', 'B.ertəsi'), ('Ç.axşamı', 'Ç.axşamı'), ('Çərşəmbə', 'Çərşəmbə'), ('C.axşamı', 'C.axşamı'), ('Cümə', 'Cümə'), ('C.ertəsi', 'C.ertəsi')], max_length=100, verbose_name='dərs günü')),
                ('add_info', models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat')),
                ('end_date', models.DateTimeField(verbose_name='Qrupun bitmə tarixi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='month_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(verbose_name='tələbə sayı')),
                ('ay_statistic', models.DateField(blank=True, null=True, verbose_name='Ay')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='müəllimin adı')),
                ('surname', models.CharField(max_length=100, verbose_name='müəllimin soyadı')),
                ('salary', models.IntegerField(verbose_name='maaş')),
                ('profession', models.CharField(max_length=100, verbose_name='ixtisas')),
                ('workpractice', models.TextField(verbose_name='iş təcrubəsi')),
                ('profilepic', models.ImageField(upload_to='profilepic/', verbose_name='profil şəkli')),
                ('teacher_id', models.IntegerField(default=1006, verbose_name='Müəllim İD')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='dogum tarixi')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='bashlama tarixi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlıq')),
                ('text', models.TextField(verbose_name='mətn')),
                ('deadline', models.DateField(verbose_name='bitmə tarixi')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='qiymət')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.group', verbose_name='qrup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.teacher', verbose_name='Taskın müəllimi')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tələbənin adı')),
                ('surname', models.CharField(max_length=100, verbose_name='soyadı')),
                ('birthday', models.DateField(verbose_name='təvəllüdü')),
                ('startdate', models.DateTimeField(verbose_name='qrupa başlama tarixi')),
                ('payment', models.IntegerField(verbose_name='Aylıq ödəniş(AZN)')),
                ('profilepic', models.ImageField(upload_to='', verbose_name='profil şəkli')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.group', verbose_name='Yazıldığı qrup')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.IntegerField(blank=True, null=True, verbose_name='aylıq ödəniş')),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='kursa başlama tarixi')),
                ('ended_date', models.DateField(blank=True, null=True, verbose_name='kursu bitirəcəyi tarix')),
                ('note', models.TextField(blank=True, null=True, verbose_name='qeyd')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='endirim')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teach.student')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='qiymət')),
                ('existence', models.BooleanField(default=True, verbose_name='davamiyyət')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teach.date', verbose_name='tarix')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.student', verbose_name='Tələbə')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.teacher'),
        ),
        migrations.AddField(
            model_name='date',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.group', verbose_name='qrupun adı'),
        ),
        migrations.CreateModel(
            name='chek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='ödəməli olduğu son tarix')),
                ('payed', models.BooleanField(blank=True, default=False, null=True, verbose_name='ödənildi')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('paymnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheks', to='teach.pay', verbose_name='ödəniş')),
            ],
        ),
    ]
