# Generated by Django 4.2.5 on 2024-02-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='month_statistic',
        ),
    ]
