# Generated by Django 4.2.5 on 2024-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_delete_month_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistic_ay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_st', models.IntegerField(verbose_name='telebe sayi')),
                ('stat_ay', models.DateField(verbose_name='Ay')),
            ],
        ),
    ]
