# Generated by Django 5.0.1 on 2024-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_alter_teacher_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dogum tarixi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bashlama tarixi'),
        ),
    ]
