# Generated by Django 5.0.1 on 2024-01-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_remove_teacher_birthday_remove_teacher_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson', models.CharField(max_length=100)),
                ('begin_date', models.DateTimeField(verbose_name='Qrupun dərsə başlama tarixi')),
                ('lesdays', models.CharField(choices=[('B.ertəsi', 'B.ertəsi'), ('Ç.axşamı', 'Ç.axşamı'), ('Çərşəmbə', 'Çərşəmbə'), ('C.axşamı', 'C.axşamı'), ('Cümə', 'Cümə'), ('C.ertəsi', 'C.ertəsi')], max_length=100, verbose_name='dərs günü')),
                ('add_info', models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat')),
                ('end_date', models.DateTimeField(verbose_name='Qrupun bitmə tarixi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.teacher')),
            ],
        ),
    ]
