# Generated by Django 5.0.1 on 2024-01-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0006_alter_teacher_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.teacher'),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tələbənin adı')),
                ('surname', models.CharField(max_length=100, verbose_name='soyadı')),
                ('birthday', models.DateField(verbose_name='təvəllüdü')),
                ('startdate', models.DateTimeField(verbose_name='qrupa başlama tarixi')),
                ('payment', models.IntegerField(verbose_name='Aylıq ödəniş(AZN)')),
                ('profilepic', models.ImageField(upload_to='', verbose_name='profil şəkli')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.group', verbose_name='Yazıldığı qrup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
