# Generated by Django 5.0.1 on 2024-01-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0008_date_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teach.journal'),
        ),
    ]
