# Generated by Django 5.0.1 on 2024-01-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0011_remove_date_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teach.date', verbose_name='tarix'),
        ),
    ]
