# Generated by Django 5.0.1 on 2024-01-22 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0012_journal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlıq')),
                ('text', models.TextField(verbose_name='mətn')),
                ('deadline', models.DateField(verbose_name='bitmə tarixi')),
                ('rate', models.IntegerField(verbose_name='qiymət')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.group', verbose_name='qrup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teach.teacher', verbose_name='Taskın müəllimi')),
            ],
        ),
    ]
