# Generated by Django 5.0.1 on 2024-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0013_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='qiymət'),
        ),
    ]
