# Generated by Django 5.0.1 on 2024-01-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0014_alter_task_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.IntegerField(blank=True, null=True, verbose_name='aylıq ödəniş')),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='kursa başlama tarixi')),
                ('ended_date', models.DateField(blank=True, null=True, verbose_name='kursu bitirəcəyi tarix')),
                ('note', models.TextField(blank=True, null=True, verbose_name='qeyd')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='endirim')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teach.student')),
            ],
        ),
    ]
