# Generated by Django 5.0.1 on 2024-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0018_alter_chek_paymnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chek',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
