# Generated by Django 5.0.1 on 2024-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0019_alter_chek_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chek',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
