# Generated by Django 5.0.1 on 2024-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0023_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='dogum tarixi'),
        ),
    ]
