# Generated by Django 5.0.1 on 2024-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0025_remove_teacher_techerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(default=1006, verbose_name='Müəllim İD'),
        ),
    ]
