# Generated by Django 5.0.1 on 2024-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0026_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
