# Generated by Django 5.0.1 on 2024-02-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0029_month_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_statistic',
            name='month',
            field=models.DateField(verbose_name='Ay'),
        ),
    ]
