version: "3.8"

services:

  db:
     image: postgres
     volumes:
       - ./data/db:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     container_name: postgres_db  

  erpapp:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: erpcourseapp:v1
    container_name: erp_cont
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db